### ISSUE TITLE
We need to update the dashboards, extracts etc. to reflect counts from ism-cache

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1071]
Now that we have proof of concept for docker-osm integration, we need to update the front page dashboards to properly reflect the docker-osm sourced data.

@meomancer suggests to at the same time update the dashboards to use the v2 API to fetch these stats which is a nice approach.

child of #1013

**Comment by meomancer** [comment]
Currently it reflects:
- count locality, also per country
- cluster when going to country page (not on world yet, need to think about handle big data of osm)
- can click loclity on country page (it will show data from osm)
- able to create new locality, it will save into docker osm cache

**Comment by timlinux** [comment]
Thanks @meomancer ! I see the country extracts are mostly not working on the map page at the moment too....otherwise it is looking good!

**Comment by meomancer** [comment]
hi @timlinux 
yes, it is not working on map 
current that are working are:
- locality number per world/country
- clustering per country (example : http://116.203.102.205/map?country=Afghanistan)

i tried to put this on all country (world map), but giving 502 because it takes a lot of time (because of osm data is quite big)
we need method for this

**Comment by meomancer** [comment]
Already fixed using this ticket : https://github.com/healthsites/healthsites/issues/1095
