### ISSUE TITLE
Activity does not update with OSM cache

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1074]
<img width="1673" alt="screenshot 2019-02-15 at 20 21 46" src="https://user-images.githubusercontent.com/178003/52876275-7371c200-315f-11e9-95ed-dc5d2a5e97fd.png">

@meomancer shouldnt we expect to see this metadata of last update changing? Otherwise we need a plan on how to fetch that....

**Comment by timlinux** [comment]
<img width="1680" alt="screenshot 2019-02-15 at 20 25 18" src="https://user-images.githubusercontent.com/178003/52876455-ee3add00-315f-11e9-9ca6-e4ea9ae97f6f.png">

Just for reference it seems the actual numbers look good - original screenshot was from our testing server, above one from production. You can see we have 2341 records when using our new osm cache.

**Comment by meomancer** [comment]
hi @timlinux 
currently, it is just showing number of data
the blocker was:
- osm database is quite big, we need method to calculate the metadata
- HS is using cache to calculate metadata, but since osm is running in background, we need some method to trigger some method to generate metadata for osm
- i'm not sure where to fetch the last updates

**Comment by meomancer** [comment]
Already fixed by using docker-osm-enrich
