### ISSUE TITLE
Mismatch between extract and database

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1075]
@meomancer I did a little testing of the Zimbabwe shapefile download and it seems there is a bit of a mismatch between what the download provides (red) and what directly querying the PG database provides (green):

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/178003/52926238-61a24180-334e-11e9-9926-e05ba8f967fd.png">

Is this simply because we have a lot of Zimbabwe data that is uploaded to HS.io that is not in OSM yet or can you see any other reason for this?

**Comment by meomancer** [comment]
hi @timlinux 
i think the missmatch one is the healthsites that can't be linked on osm (can't be found on osm)
i haven't created it on osm, because we need method to link it (because when we create on osm, there is no osm_id and osm_type yet)

currently i do a test to create osm data when healthsite is created, by link with the pk of osm record

**Comment by meomancer** [comment]
did you query through HS data?
i think the missmatch one is those healthsites can't be linked on osm (can't be found on osm)
i haven't created it on osm, because we need method to link it (because we need to create osm data but there is no osm_id to be linked)

currently i do a test to create osm data when healthsite is created, by link with the pk of osm record

**Comment by meomancer** [comment]
this is already fixed, because we are already using osm data (without using old healthsite anymore)
