### ISSUE TITLE
please fix travis error

### ISSUE THREAD

**Issue by meomancer** [healthsites/healthsites#1111]
# Problem
Currently we have additional database that created not from django (no migrations for this), making travis test error

# Solution
Please fix this

**Comment by ann26** [comment]
hi @meomancer and @myarjunar 

I created a PR in #1112 
It fixed:
- flake8 error
- removed unused codes
- fixed some test
- fixed test settings for travis

The error in travis initially was because the ones I have fixed in the PR and docker_osm db error.
Thus, I removed the docker_osm db from the settings and use mock instead.
This however, works in my local machine but not in travis which confused me.
