### ISSUE TITLE
Twitter login gives a 500

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1166]
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/178003/58019669-f78c6a80-7afd-11e9-8607-179038447c60.png">

https://staging.healthsites.io/login/twitter/?next=/map

**Comment by ann26** [comment]
hi @timlinux @meomancer 
this is because the social auth key and secret for facebook and twitter are not available in staging. 
maybe we can use Kartoza account to get this?

the facebook social auth key and secret can be obtained by registering new app in this url: https://developers.facebook.com/apps/ and then see the app's key and secret in settings

the twitter social auth key and secret can be obtained by registering new app in this url:
https://developer.twitter.com/en/apps and then see the app's key and secret from the dashboard

**Comment by meomancer** [comment]
hi @markherringer 
could you check @ann26 comment above, please?

**Comment by ann26** [comment]
we don't use twitter login anymore
