### ISSUE TITLE
Duplicate management requirements

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1265]
These are the things we need to do to provide a good user experience within the scope of the current project:

1) In the map view, prevent submissions that may be duplicates unless the user explicitly indicates that it is not a duplicate and chooses to submit their record anyway.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/178003/61460037-e0cf8c00-a965-11e9-9fa3-3c5e430e81dd.png">

2) In the user profile area, any submissions made by Gather that appear to be duplicates should be shown as a list with a button next to each that will take you to the edit panel on the map for that record. 

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/178003/61460901-9949ff80-a967-11e9-86e5-e401ce09baef.png">

3)

When the map is shown for a suspected duplicate, the other facility(s) which are suspected to be the complementary set of duplicate suspects should be highlighted on the map.

<img width="1680" alt="Screenshot 2019-07-18 at 14 27 19" src="https://user-images.githubusercontent.com/178003/61461411-88e65480-a968-11e9-8093-6dc3246fc90b.png">

4) Staff users should be provided a view that shows all records in conflict, same experience as for 2) above but lists all conflicted records for all users. When the staff user resolves the conflict if the resolution is to submit the record, the record should be submitted in the name of the original user.

**Comment by mnoblecourt** [comment]
Thanks for the suggestion Tim, I think that solves a large part of the problem.
As discussed on the phone, what would be very useful next is a proper conflict resolution tool like in JOSM (keep the original point but choose which attributes one keeps).

In the meantime, for our current survey and since all (or almost all) the duplicates we'll gate will be healthsites with very limited data (name/coordinates) replaced by the same facility but with a lot of attribute data, the simplest would be to automatically keep the original OSM object (=ID) while replacing all the attributes by the new record's (please make sure the accents are kept in the process), and remove the new record after. This way we both save the history of the object in OSM, and easily add the attribute data we collected (since manual copy-pasting would be very time consuming); in case we happen to loose an attribute that was more precise before (very unlikely), we can always find it back on the OSM history of said object.
If we can have this work around implemented for the workshop next Tuesday that would be great, since we'll be demonstrating the results in Healthsites.io.

**Comment by mnoblecourt** [comment]
Actually I just checked on the OSM database extract, there is no data at all the will be lost since we re-collected all the fields that were there in existing data, so we should always have data more recent!

**Comment by timlinux** [comment]
Based on our conversations with @mnoblecourt and @meomancer we propose to add another button to the dialog:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/178003/61522057-76702780-aa09-11e9-94e3-f47dc6687c4e.png">


This will let you replace the original record's attributes, discard the new record and keep the original OSM ID thus maintaining its history.

**Comment by timlinux** [comment]
After discussion with @meomancer we came up with this:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/178003/61522790-f77bee80-aa0a-11e9-888c-92203d044008.png">

**Comment by mnoblecourt** [comment]
Thanks @timlinux, looks good to me! I suppose we'll have to test it anyway to see if there aren't situations we didn't anticipate.
I found another aspect that is not a pressing issue since we're not deleting any data but still will generate duplicates: we create all our health sites as nodes while some are already mapped as polygons. This will be harder to handle I imagine...

**Comment by meomancer** [comment]
this system done in https://github.com/healthsites/healthsites/pull/1260
