### ISSUE TITLE
avoid creating empty changesets

### ISSUE THREAD

**Issue by tyrasd** [healthsites/healthsites#1360]
This is a thing I overlooked in #1344. It's not a major bug, but it would be great to avoid the creation of empty changesets (i.e. changesets without any changes at all) like the following ones:

* https://www.openstreetmap.org/changeset/82280413 by @meomancer 
* https://www.openstreetmap.org/changeset/82263865 by @markherringer 
* https://www.openstreetmap.org/changeset/82271923 by @timlinux
* https://www.openstreetmap.org/changeset/82261033 by @milovanderlinden 
* https://www.openstreetmap.org/changeset/82260969
* https://www.openstreetmap.org/changeset/82260957

**Comment by meomancer** [comment]
the problem was the previous one, it was create new changeset but fail to update the way/node
it is because 
https://github.com/healthsites/healthsites/issues/1350

It should be fixed by this PR
https://github.com/healthsites/healthsites/pull/1359
which will check the availability node/way before create changeset

**Comment by tyrasd** [comment]
ah, ok. that makes sense.
