### ISSUE TITLE
latest updates

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#258]
As I user I want to see 'who' has made the most 'recent' location updates and 'what' they were.

The list should show the last five updates. The most recent update must be at the top of the list.

The Update:
2015-10-14 17:23:15 - @who - Murambi CS
[when] [the user who made the update] [a link to the update]

Present a full timestamp indicating [when]:
2015-10-09 17:23:15 

Two links should be presented:
[@jimbob] - [75 hs/added 20/amended]

The user [the user who made the update]
@jimbob
Link to the users profile page.

The update [a link to the update]
75 hs/added 20/amended
Open the map and show the location/s

Which update was it? Two options:
1) 75 HS added. Therefore '75 hs loaded'
2) 20 hs amended. Therefore '20 hs amended'

Notes:
How do we present multiple updates on the map
Do we only show the locations that have been updated?
How should we do this? Different colour marker?

http://healthsites.mashastudio.net/#

**Comment by meomancer** [comment]
could you explain me about link 2?

**Comment by timlinux** [comment]
@markherringer and @meomancer We don't have everything in place for this. Can we please first focus on the simple easy to implement things that provide high value (e.g. making all links in the menu bar work, making the map interactive, making search work). That will also let @meomancer ramp up so that he has the needed background and experience to work on more complex tasks like this one.

**Comment by meomancer** [comment]
@markherringer already fix and push staging
