### ISSUE TITLE
hospitals not appearing in OSM import 

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#330]
As a healthsites user I expect to see the healthsites pin above each and ever hospital, clinic and orthopedic location on the map.

Bug: Currently there are locations presented on OSM that have not been imported into healthsites.

Here is the original data dump and query.
https://github.com/healthsites/healthsites/wiki/Data-provider---OSM

Link to location in question on OSM:
https://www.openstreetmap.org/edit?editor=id&relation=536765#map=19/-4.63147/55.45517

Link to location on healthsites:
http://staging.healthsites.io/map#!/locality/96ed1cf7f6d94d5f946f109b05a93f81

![seychelles](https://cloud.githubusercontent.com/assets/38838/11343590/9e0ed3fc-9204-11e5-8d67-9d8def5afb46.png)

Notes:
Please amend new OSM import to include for Orthopaedic clinics #317

**Comment by timlinux** [comment]
Ok so I think the issue is that the hospital in question is captured on OSM as a polygon feature and is not being pulled out by our osm export. The nearby location for the dental clinic is a point feature.

![selection_002](https://cloud.githubusercontent.com/assets/178003/11365669/9eea5808-92b0-11e5-90d9-1afbd883fb74.png)

![selection_005](https://cloud.githubusercontent.com/assets/178003/11365681/b2139da4-92b0-11e5-9158-5f309cabed97.png)

Versus (point clinic):



![selection_003](https://cloud.githubusercontent.com/assets/178003/11365683/b605588a-92b0-11e5-97b6-e451462d1fa3.png)

![selection_004](https://cloud.githubusercontent.com/assets/178003/11365687/bca6874a-92b0-11e5-972c-72a402cbfac2.png)

We will need to run another extract for polygon features and then import them.

**Comment by Gustry** [comment]
I can have a look to this issue. Do I have to perform the extract ? I guess there is a script somewhere with the query ?

**Comment by markherringer** [comment]
In addition to addressing the missing polygon please could we query for as many of the attributes listed here:
https://github.com/healthsites/healthsites/wiki/OSM-data-import

**Comment by markherringer** [comment]
here is a working doc shared by the HOT team: https://hackpad.com/Uganda-Bureau-of-Statistics-Health-and-Education-facilities-import-hjoRNhGzDjj
See..'LEVEL: Type of facility (indicates size/capabilities). Can be used to derive value for `amenity` key (`clinic`, `hospital`'

**Comment by Gustry** [comment]
It's fixed. 47 854 hospitals and clinic have been imported today. They were described as polygons in OSM.
