### ISSUE TITLE
Masterisation -  identifying one and only one canonical record per health facility

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#523]
https://docs.google.com/document/d/1iE5zqgfh1JmQpPBQ9A4IrTdX1HcZx98ZWHuDR0wnhYU/edit?usp=sharing

**Comment by meomancer** [comment]
Current story
Now our locality can be flagged as synonym or master. It can be changed in edit mode

here is test case :
- we have : **Rumah Sakit Bhayangkara Sartika Asih**
![screenshot from 2016-03-28 16 32 09](https://cloud.githubusercontent.com/assets/4530905/14075430/52dc78e6-f503-11e5-93fb-cb91f3c18dd3.png)

- than we have : **Klinik IT Telkom**. We want **Rumah Sakit Bhayangkara Sartika Asih** as it's master. Here is the screenshot how to set it.
![screenshot from 2016-03-28 16 32 26](https://cloud.githubusercontent.com/assets/4530905/14075445/7beaef9c-f503-11e5-9f56-0afb53d26896.png)
![screenshot from 2016-03-28 16 32 35](https://cloud.githubusercontent.com/assets/4530905/14075444/7be99f02-f503-11e5-9ca3-f11d8d89e4be.png)
![screenshot from 2016-03-28 16 32 39](https://cloud.githubusercontent.com/assets/4530905/14075446/7beca648-f503-11e5-9dc9-9efdfd0265c7.png)
![screenshot from 2016-03-28 16 32 42](https://cloud.githubusercontent.com/assets/4530905/14075447/7beef6dc-f503-11e5-8fc0-3101c7c71b51.png)
![screenshot from 2016-03-28 16 32 51](https://cloud.githubusercontent.com/assets/4530905/14075494/d7f019ca-f503-11e5-88f2-0f754b91a25c.png)


- but we want to set **Rumah Sakit Bhayangkara Sartika Asih** has master
- and we decide **Rumah Sakit Pindad** as **Rumah Sakit Bhayangkara Sartika Asih**'s master
![screenshot from 2016-03-28 16 34 03](https://cloud.githubusercontent.com/assets/4530905/14075523/0e4f60c0-f504-11e5-82cd-90e94001394b.png)

- here is **Rumah Sakit Bhayangkara Sartika Asih** info
- and because **Klinik IT Telkom** has **Rumah Sakit Bhayangkara Sartika Asih** as master, it will change it's master to **Rumah Sakit Bhayangkara Sartika Asih**'s master too
![screenshot from 2016-03-28 16 35 57](https://cloud.githubusercontent.com/assets/4530905/14075540/34be9cb2-f504-11e5-862d-2077858cd4df.png)

The backend already handle based on story in document
