### ISSUE TITLE
Oauth not working

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#573]
Social handle sign on status:
Linkedin is working (Mark)
Facebook is working (Graeme)
Twitter is not working (Mark)
Google is working but with the number added (MARKD9494A71A9844CE0)

**Comment by meomancer** [comment]
@markherringer i tried signin google, linkedin and github
it said that the redirect urls is missmatch

could you please update redirect url to : https://staging.healthsites.io/?
and give me the key?

**Comment by meomancer** [comment]
hello @markherringer 
about "Google is working but with the number added (MARKD9494A71A9844CE0)"
it is because "MARK" id is already used and django-social-auth is not allowed to have 2 account that has same name. That why they generate uuid after username.
for twitter and facebook, i save "screen name" or "name" from response that they give, but google doesn't provide it

Need advise from @ismailsunni

**Comment by timlinux** [comment]
In #889 we would need an architecture change:

* OSM becomes the primary (only) means to log in to the site (needed for editing via OSM API)
* Other social logins can be associated with the site for purposes like:
 * Tweeting a record
 * Facbooking a dooda whatsit
 * Doing a data extract straight to your google drive

**Comment by meomancer** [comment]
we are using osm now and it is working
