### ISSUE TITLE
include HXL tags in healthsites

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#883]
As a healthsites data adminstrator I want to include HXL tags in healthsite data so that I can improve information sharing during a humanitarian crisis

https://docs.google.com/spreadsheets/d/1QzFSUWz6PoiKRqhVXwYEteXV2H8GIaCFpV8Z_IovccA/edit?usp=sharing 

http://hxlstandard.org/
http://docs.humdata.org/hdx-python-library/
http://hxlstandard.org/standard/1_0final/dictionary/

**Comment by davidmegginson** [comment]
Thanks -- great story. Here are some possible drill-downs for "improving information sharing":

* Users want to be able to validate incoming data automatically
* Users want to be able to combine healthsites data with data from other sources (e.g. population of each district)
* Users want to be able to generate maps or charts from healthsites data
* Users want to use healthsites data as master data for something else (e.g. tracking the progress of a health-ministry project to provide infection prevention and control training to all health facilities in the country)
* Users want to aggregate healthsites data to include in their own reports or dashboards

Does any of these ring true? Anything I might have missed.

**Comment by timlinux** [comment]
Hi @davidmegginson 

How do you envisage linking data in HXL with OSM data. Generally OSM don't like it when we store third party ID's in OSM records. So a neat way would be to store the OSM id in every HXL entry. We could come up with a tool to harvest those id's (e.g. by using a simple proximity algorithm based on the HXL coords and the OSM coords) and them give you back a join table with HXL_ID <--> OSM ID. I don't know if this is going to work - my understanding of HXL is quite basic....

Bear in mind that the OSM id can sometimes change - mainly when a point feature is turned into a way (e.g. a building point -> building footprint).

**Comment by davidmegginson** [comment]
There is currently a collaboration underway between HDX and the Humanitarian OpenStreetmap Team. I will check to see how they're planning to handle the relationship between UN humanitarian p-codes and OSM features. They might already have started a discussion in the broader OSM community about allowing p-codes as a special case.

But otherwise, yes, I think your plan makes sense. Both the HXL standard and the toolchain have good support for mapping tables, and if you were generating/updating them automatically from your database, we wouldn't have to worry that the mappings were getting stale.

**Comment by davidmegginson** [comment]
Hi, Tim. I checked with our team, and there are no plans to involve P-codes in our current integration work with the HOT, though we realise that's a big omission.

Since P-codes—while flawed in many ways—are really our only hope for geo-level data interoperability during a humanitarian crisis, I wonder if the OSM community might be willing to at least consider a humanitarian exception for outside coding systems for administrative divisions and facilities. I don't expect it would be an easy lift, but do you think it's worth even trying?

**Comment by bgirardot** [comment]
I believe there might already be an exception for p-codes let me look.

My understanding is that OSM objects to is "one offs" for external coding systems, private systems or application specific id's.

International standards there is more understanding for I think. As I said, let me research, I think p-codes might have already been discussed.

**Comment by bgirardot** [comment]
yes, unocha:pcode is in use in OSM now (33k uses) and was discussed on the OSM Imports list in 2014 with very little objection.

https://wiki.openstreetmap.org/wiki/P-Codes
https://lists.openstreetmap.org/pipermail/imports/2014-September/003450.html
https://taginfo.openstreetmap.org/keys/unocha%3Apcode

**Comment by davidmegginson** [comment]
Thanks, Blake. I think that would be a big step for bringing OSM data more
into the humanitarian system. Of course, the onus is now on UN OCHA and
agencies to do a lot better job managing and publishing those p-codes
(which are currently mostly hidden in shapefiles).


Cheers, David

**Comment by bgirardot** [comment]
When we first started discussing the healthsites.io data lifecycle, I mentioned that with the support and backing of icrc, ifrc, healthsites.io could implement its own coding system for health sites. I proposed calling them h-codes :)

Not sure if that idea helps at all, but as I said, i think if the icrc + ifrc back a healthsites.io based coding system for health sites to help facilitate data exchange and the osm->healthsites.io->osm->healthsites.io-> etc data cycles it would be accepted by OSM.

If all these health sites already have pcodes, that is great, even better, but if that is not the case and healthsites.io needs to create something, if it was recognized and used by significant humanitarian orgs I think OSM would be ok with it. No promises of course, but based on the pcode experience, seems possible.

**Comment by davidmegginson** [comment]
All good news! The biggest challenge is that p-codes are locally managed, sometimes by the OCHA office (if there is one), or sometimes by a big lead agency like UNHCR or UNICEF, so they'd have to be approved on a country-by-country basis. If we can make this work, then healthsites.io data could be useful (even essential) for MoH data systems places like Guinea or Sierra Leone, but it's not an easy lift. Perhaps it would make sense to try piloting in a single country: I know that Guinea and Sierra Leone are currently in the process of implementing DHIS2 health systems and developing facilities master lists, so one of them might be a good pilot partner.

**Comment by davidmegginson** [comment]
Just to give some context, back in 2015 during the Ebola crisis, we had facilities lists for Guinea from the MoH, from the Volunteer Standby Task Force, from UNICEF, and (IIRC) a few others, representing a huge human effort, but without shared codes, we had no way to use them for the response (we tried various clever name- and location- matching strategies, but never got above about 20%). We ended up having to ignore the much-better UNICEF list and stick with the MoH one, even though it was a out of date, and also omitted most informal health facilities.

**Comment by markherringer** [comment]
@davidmegginson agree that we nee to pilot this process

**Comment by markherringer** [comment]
https://www.humanitarianresponse.info/en/applications/tools/category/implementing-p-codes

**Comment by smit1678** [comment]
@davidmegginson Are unique p-codes being generated to track individual facilities? From my understanding, I thought it was a bit more like a zipcode system. So multiple facilities could have the same p-code since they are in the same settlement area. I think this is right, but want to clarify. 

From an OSM angle, I think p-code tags for settlements or admin units I think is great. Having them managed locally is also helpful since they can better match any changes in the local admin units and then feed those changes back up into OSM. 

From a health facilities tagging within OSM, I'm not sure we should tag every health facility with it's matching p-code. I'm thinking that the project should look to use a local standard, like a MOH national registry ID, as an external ID tag beyond any OSM ID or Healthsites ID. That ID can be managed locally as well. Then Healthsites can help map the facilities to p-codes as @timlinux mentioned and provide a lookup table. This way the project then can then help connect to a UN systems, MOH systems, and then any systems that lean on OSM IDs.

**Comment by bgirardot** [comment]
Best practices is that pcodes are no longer generated based on smaller administrative boundaries, perhaps not based on any admin boundaries. It has been a while since I researched this. But the issue was that admin boundaries changed too often and meant pcodes based on them became out dated too often.

I think they are meant to be somewhat permanent and universally used.

My understanding is that the important part is that we have a unique code to help with matching between healthsites.io and OSM. That is why I think we might even be better using out own reference id number if pcodes do not work. But OSM would need that code to somewhat generally accepted and recognized by other organizations.

**Comment by todrobbins** [comment]
Hello all, just getting caught up on this issue. Is there any kind of existing registry of p-codes online? Or is it a loose collection of ids that may have overlap/redundancy? I'm curious how well managed the codes are at this point.

Also, I think that the p-codes could serve as that match between healthsides.io and OSM ids if we can confirm the specificity of the p-code (How precisely are p-codes assigned? To actual structures/complexes or more like ZIP codes like @smit1678 mentioned).

Thanks for your work on this thus far!

**Comment by todrobbins** [comment]
PS: here's the full document describing the p-code schemas: https://www.humanitarianresponse.info/system/files/documents/files/FieldGuideForTheUseOfGeo-Codes.pdf

**Comment by todrobbins** [comment]
Analyzing [this p-code](https://overpass-turbo.eu/?w=%22unocha%3Apcode%22%3D%22GIN0040050800062%22+global&R), it does look like the p-codes are applied at a higher level than might be useful for mapping to healthsites ids.

See also: https://overpass-turbo.eu/?w=%22unocha%3Apcode%22%3D%22GIN0010020900002%22+global&R

**Comment by todrobbins** [comment]
Looks like the _Field Guide_ actually suggests that as

> P-codes are introduced and applied, all the data referring to settlements or features belonging to a settlement will have a unique code to identify them, like schools and __health clinics__ in a specific area. (emphasis mine) 

So could this be a advanced by working with field officers to generate P-codes for health clinics that would then map directly to healthsites ids?

**Comment by davidmegginson** [comment]
P-codes are not well organised yet, though OCHA's HDX project (with a partner) are gradually working to improve them. Right now, you can find all of the available _Common Operational Datasets_ (CODs) here, including the p-codes as attributes on the admin boundary shapes:

https://data.humdata.org/search?ext_cod=1

Each individual country IM Working Group (coordinated by the country or regional OCHA office) has responsibility for collecting these, so it's a slow process getting them standardised. We're hoping eventually to have the p-codes for every target country extracted into a CSV or XLSX file for non GIS specialists.

As for level, it depends on the country. Some go only down to admin level 2, while some go down to admin 5. Some assign p-codes to individual (small) settlements and camps, while some don't.

I'm CC'ing my colleague @cjhendrix , who's our lead on geodata. When he's back from parental leave, he might have some more information to add.

**Comment by ivangayton** [comment]
Hi all, sitting with Mark in Dakar now, and he suggested I add my verbal comment here:

HXL use requires the addition of a second header row. This runs counter to every instinct I possess related to data organisation; it means you have to tell every piece of software you're working with that you've got two header rows.

Why can't we add the HXL tag as a suffix to the top row?

Instead of:

|District|Cluster|Beneficiaries|
|---|---|---|
|#adm1|#sector|#affected|
|data|data|data|
|data|data|data|

Why not:

|District #adm1|Cluster #sector|Beneficiaries #affected|
|---|---|---|
|data|data|data|
|data|data|data|

The hashtag then functions a bit like a comment marker in Python (or maybe better to say it functions like a decorator in Python); it's pretty obvious that it's not part of the column name, and it avoids the necessity of adding a second header row.

I've just spoken with Amadou at the DataSkills workshop in Dakar, who tells me that he deletes the second header row in order to play with datasets in Excel, and the replaces them afterward. This is not efficient! Very few software packages will be happy with datasets with two header rows.

There is an obvious disadvantage to the suffix method: it creates wide columns in spreadsheets. That's a hassle, for sure. However, it can be mitigated by word wrapping, or by shrinking the columns so that the tag isn't visible.

It shouldn't be hard to tell any parser to look for a hashtag within the header row, and I can't think offhand of any dataset I've ever seen with hashtags in the header row being used for anything else.

I realize that the HDX spec has been around for a while now, and it might not be possible to change things now without breaking a lot of stuff, but would it be possible to at least allow this format?

**Comment by davidmegginson** [comment]
Thanks for sharing that, Ivan. Since I come from a similar background, my
original proposal was similar to your suggestion (except using numeric
codes; we hadn't hit on hashtags yet). However, the working group decided
back in 2014, after running through a lot of different options, that the
separate row was the better (though not perfect) choice. Here are some of
the considerations:

   - Many (most?) handwritten humanitarian-data spreadsheets already have
   multiple rows of text headers before the data. It's generally only API
   output or database exports that has limit themselves to a single header row.
   - A row of hashtags gives us a clear delineation between the end of the
   headers and the start of the data.
   - A separate hashtag row can be hidden from ordinary users (e.g. in an
   Excel template), while appended text in individual cells cannot.
   - Additions to text headers (like my proposed codes) make the headers
   longer and messier, and increase the risk of users accidentally or
   deliberately changing them.
   - For database/API-type applications, you can still exclude the text
   headers and include *just* the HXL hashtags (it's OK for them to be the
   first row of the dataset).

There were going to be disadvantages either way, but we decided that our
primary audience was people creating data by hand—where the bulk of
humanitarian data exists and is currently mostly inaccessible—so we decided
to reduce their effort and load the extra effort on to the (much-smaller
and more technically-competent) audience of software developers and
database managers. To help mitigate that problem slightly, the HXL Proxy
can strip the text headers from any HXL dataset on the fly, so you can use
a URL pointing to the proxy to get a dynamic copy of the dataset with only
one header row.


Cheers, and apologies for the extra hassle,


David

**Comment by ivangayton** [comment]
Hi David,

Thanks for your amazingly prompt and well thought-out reply! Indeed I agree with the principle that we should prioritise the needs of manual users over the teched-up. I also agree that there's fragility in using suffixes within columns (and risk that users will mess with them). 

I do question the extent to which the primary audience is still creating data by hand, or for how long this will continue to be the case! I'm seeing more and more people in low-income settings, where we would only a few years ago never have considered electronic data entry, where local people are converting to electronic methods. If not Excel, it's OpenDataKit or webforms on a tablet...  I understand you're a fellow Canadian; you may remember the hoary old quote "... skate to where the puck is going to be, not where it has been." The puck is going to electronic data entry, and perhaps we need to think about what best serves those who are newly adopting electronic data entry!

No problem for the hassle, and thanks for your work on this!

Ivan

**Comment by ivangayton** [comment]
Hi David,

Thanks for your amazingly prompt and well thought-out reply! Indeed I agree with the principle that we should prioritise the needs of manual users over the teched-up. I also agree that there's fragility in using suffixes within columns (and risk that users will mess with them). 

I do question the extent to which the primary audience is still creating data by hand, or for how long this will continue to be the case! I'm seeing more and more people in low-income settings, where we would only a few years ago never have considered electronic data entry, where local people are converting to electronic methods. If not Excel, it's OpenDataKit or webforms on a tablet...  I understand you're a fellow Canadian; you may remember the hoary old quote "... skate to where the puck is going to be, not where it has been." The puck is going to electronic data entry, and perhaps we need to think about what best serves those who are newly adopting electronic data entry!

No problem for the hassle, and thanks for your work on this!

Ivan

**Comment by davidmegginson** [comment]
That's a timely point, especially because there's work starting right now
to integrate native HXL support into KoBo. The workflow that comes out of
that might influence HXL's future direction.

**Comment by davidmegginson** [comment]
Hi, everyone. I hope that all of you north of the tropics had a good summer, and that the rest of you had good seasons of various kinds. :)  I'm about to leave for a week, but when I get back, how can I help restart this now that we're back at our desks?

**Comment by meomancer** [comment]
now we can show hxl data on api
healthsites.io/api/v2/facilities/?output=geojson&page=1&flat-properties=True&tag-format=hxl

just change tag-format parameter
